// Server-side session lifecycle, layered over the SessionStore seam (store.ts):
// create a session, fetch its access token with a silent refresh when stale,
// and delete it. The access/refresh token split lives here — the browser only
// ever holds an opaque session id; both tokens stay server-side in the store.
// This module reaches GitHub only indirectly, through oauth.ts's `refresh`.
import type { Config } from "./config";
import type { Identity, SessionData, SessionId, SessionStore } from "./store";
import { asSessionId } from "./store";
import { refresh } from "./oauth";
import { fetchIdentity } from "./identity";
import * as arctic from "arctic";
import { getLogger } from "@logtape/logtape";

const log = getLogger(["htmldoc-review", "session"]);

export type { SessionData, SessionId } from "./store";

// The current session-record shape. Stamped onto every write by persist(); a
// pre-identity record read from KV has no `version` and is treated as 1.
const CURRENT_VERSION = 2;

// DEFAULT_TTL is the session's lifetime when GitHub doesn't tell us the refresh
// token's horizon: 180 days, matching GitHub's default refresh-token validity.
// SKEW_MS is a clock-skew safety margin — we treat the access token as expired
// 30s before its real expiry so a token that looks valid here can't expire in
// flight between this check and GitHub serving the request.
const DEFAULT_TTL = 60 * 60 * 24 * 180;
const SKEW_MS = 30_000;

// A token grant handed to persist(): the fresh GitHub token triple plus the KV
// expirationTtl (seconds) the record should live for. The `expires_at` is the
// ACCESS token's short expiry (ms); `refresh_ttl` is the long refresh horizon.
export interface Grant {
  access_token: string;
  refresh_token: string;
  expires_at: number; // ms
  refresh_ttl: number; // seconds, for KV expirationTtl
}

function refreshTtlOf(tokens: arctic.OAuth2Tokens): number {
  const t = Number((tokens.data as Record<string, unknown>).refresh_token_expires_in);
  return Number.isFinite(t) ? t : DEFAULT_TTL;
}

/**
 * The ONLY constructor of a SessionData — every write path (new login, token
 * refresh, lazy identity backfill) routes through here, so no site can hand-build
 * a record and let the fields drift. Field provenance:
 *   - version:  STAMPED — re-set to CURRENT_VERSION on every write.
 *   - iat:      PINNED   — minted once (prior?.iat ?? now) then carried forever;
 *               a refresh must NEVER bump it, or an active user could dodge the
 *               SESSION_VALID_SINCE cutoff by simply staying logged in.
 *   - identity: PINNED/CARRIED — kept from the prior record unless a caller
 *               supplies a fresher one (login capture, or a lazy backfill).
 *   - token triple: SUPPLIED — arrives fresh from GitHub in the grant each write.
 * `prior` is the record being replaced (null = brand-new login). The KV TTL comes
 * from grant.refresh_ttl.
 */
export async function persist(
  store: SessionStore,
  id: SessionId,
  grant: Grant,
  prior: SessionData | null,
  identity?: Identity
): Promise<SessionData> {
  const data: SessionData = {
    version: CURRENT_VERSION,
    iat: prior?.iat ?? Date.now(),
    identity: identity ?? prior?.identity ?? null,
    access_token: grant.access_token,
    refresh_token: grant.refresh_token,
    expires_at: grant.expires_at,
  };
  await store.put(id, data, grant.refresh_ttl);
  return data;
}

/**
 * Build a Grant that re-persists an existing record UNCHANGED (token triple as-is)
 * — used by the lazy identity backfill, which has only the stored record, not the
 * arctic tokens. The TTL is pinned to DEFAULT_TTL, NOT a value derived from
 * expires_at (the ACCESS-token expiry) — deriving from expires_at would truncate
 * the KV record to ~hours and evict a live session; the iat cutoff, never the TTL,
 * is the logout lever. DEFAULT_TTL re-sets the full 180-day horizon on a session
 * we KNOW is live (we just used its token to fetch /user), so the upgrade can only
 * lengthen the record's life, never shorten it. A true v1 legacy record never
 * stored its refresh horizon anyway, so "read it back" is impossible — DEFAULT_TTL
 * is the safe-side floor (GitHub's own default refresh validity).
 */
function grantFrom(record: SessionData): Grant {
  return {
    access_token: record.access_token,
    refresh_token: record.refresh_token,
    expires_at: record.expires_at,
    refresh_ttl: DEFAULT_TTL,
  };
}

export async function createSession(
  store: SessionStore,
  grant: Grant,
  identity?: Identity
): Promise<SessionId> {
  // Session id = one crypto.randomUUID(). Per OWASP Session Management, a
  // session id must be generated by a CSPRNG and carry >= 64 bits of entropy;
  // a v4 UUID is CSPRNG-backed with 122 random bits, comfortably clearing the
  // floor, so a single UUID suffices (no need to concatenate two). The id is
  // opaque — it's only a lookup key into the server-side store, never a token.
  // Minting stays here; the record write delegates to the single persist() writer
  // (prior = null → mints iat, stamps version, carries the login-time identity).
  const id = asSessionId(crypto.randomUUID());
  await persist(store, id, grant, null, identity);
  return id;
}

/**
 * Decide whether an arctic error from a refresh means "the grant is dead"
 * (force re-login) versus "transient/unknown" (must surface). A bad/expired/
 * revoked refresh token comes back as OAuth2RequestError (200 + error body) or,
 * for a non-200 token response, UnexpectedResponseError /
 * UnexpectedErrorResponseBodyError in arctic v3. A network failure
 * (ArcticFetchError) is NOT a dead grant.
 */
function isDeadGrant(e: unknown): boolean {
  return (
    e instanceof arctic.OAuth2RequestError ||
    e instanceof arctic.UnexpectedResponseError ||
    e instanceof arctic.UnexpectedErrorResponseBodyError
  );
}

/**
 * Refresh the access token for session `id` and persist the result.
 *
 * Returns the new access token, or `null` to signal "force a full re-login".
 *
 * Shape check (arctic v3): `refresh()` -> `GitHub.refreshAccessToken` -> an
 * `OAuth2Tokens`; we read `accessToken()`, `refreshToken()` (GitHub rotates the
 * refresh token, so we persist the NEW one), and `accessTokenExpiresAt()`.
 *
 * Refresh race (known D1 limitation): with no Durable Object to serialize
 * refreshes, two concurrent requests can both see an expired token; the first
 * rotates the refresh token, and the second's now-stale token fails as a dead
 * grant. So on a dead grant we RE-READ the session once: if a concurrent
 * request already rotated to a fresh, unexpired token, we use it instead of
 * nuking a perfectly good session. Only if the re-read is also gone/expired do
 * we purge and force re-login. A residual race remains (two refreshes can still
 * interleave between the re-read and the delete); accepted without a DO.
 */
async function doRefresh(
  cfg: Config,
  store: SessionStore,
  id: SessionId,
  prior: SessionData
): Promise<string | null> {
  try {
    const tokens = await refresh(cfg, prior.refresh_token);
    // Route the write through the single persist() chokepoint with the whole
    // prior record: iat is pinned (carried, never bumped) and identity carried,
    // so a refresh can neither dodge the cutoff nor lose the captured name.
    const grant: Grant = {
      access_token: tokens.accessToken(),
      refresh_token: tokens.refreshToken(),
      expires_at: tokens.accessTokenExpiresAt().getTime(),
      refresh_ttl: refreshTtlOf(tokens),
    };
    const next = await persist(store, id, grant, prior);
    return next.access_token;
  } catch (e) {
    // A network failure must NOT nuke the session -- let it surface as 5xx.
    if (e instanceof arctic.ArcticFetchError) throw e;
    if (!isDeadGrant(e)) throw e;

    // Possible dead grant. Before purging, re-read once: a concurrent request
    // may have already rotated the token (refresh-race window above).
    const reread = await store.get(id);
    if (reread && Date.now() < reread.expires_at - SKEW_MS) {
      log.info("session refresh lost a race; using concurrently-rotated token", {
        sessionId: id,
      });
      return reread.access_token;
    }

    // Genuinely dead refresh token: purge the session and force a full
    // re-login. Log the session id and error class only -- never the refresh
    // token. Preserve the original arctic error as `cause` so it is not
    // swallowed (e.g. for a future Sentry/breadcrumb hook).
    const cause = e instanceof Error ? e : undefined;
    log.error("session refresh failed; purging session", {
      sessionId: id,
      error: cause?.constructor.name ?? typeof e,
      cause: new Error("refresh token rejected", { cause }),
    });
    await store.delete(id);
    return null;
  }
}

export async function getValidAccessToken(
  cfg: Config,
  store: SessionStore,
  id: SessionId,
  forceRefresh = false
): Promise<string | null> {
  const s = await store.get(id);
  if (!s) return null;

  // Forced-re-login cutoff: a record whose login-time iat predates
  // SESSION_VALID_SINCE is deleted-on-read and treated as gone (null is already
  // the universal "send them through login" signal, so no new logout path). A
  // legacy record with no iat reads as 0, so bumping the cutoff catches it too.
  if ((s.iat ?? 0) < cfg.sessionValidSince) {
    await store.delete(id);
    return null;
  }

  if (!forceRefresh && Date.now() < s.expires_at - SKEW_MS) {
    return s.access_token;
  }

  // Pass the WHOLE record so the refresh carries pinned iat + identity forward.
  return doRefresh(cfg, store, id, s);
}

/**
 * Resolve the reviewer's captured identity for session `id`, backfilling it on
 * read for a pre-identity (or failed-login) record. If the record already carries
 * an identity, return it with no GitHub call. Otherwise fetch GET /user with the
 * already-resolved `token` and persist it in place (single write-back via persist,
 * upgrading version->2 and carrying the token triple + pinned iat). Backfill keys
 * on a MISSING identity, not a raw version check, so it heals both true v1 records
 * and a v2 record whose login-time capture failed.
 *
 * Returns null ONLY when the record is gone. A fetchIdentity failure is NOT
 * swallowed here — it propagates (surfaces as 5xx) rather than stamping a
 * placeholder onto a real reviewer's session. The record is left untouched (no
 * delete, no placeholder write), so the next request simply retries the backfill.
 */
export async function getIdentity(
  cfg: Config,
  store: SessionStore,
  id: SessionId,
  token: string
): Promise<Identity | null> {
  void cfg; // reserved for symmetry with the other session helpers; unused today
  const record = await store.get(id);
  if (!record) return null;
  if (record.identity) return record.identity;

  const identity = await fetchIdentity(token);

  // TOCTOU guard mirroring doRefresh's re-read-before-write invariant: `record`
  // is a snapshot taken BEFORE the /user round-trip, and a concurrent doRefresh
  // may have rotated the token triple in the meantime. Re-read so we stamp
  // identity onto the CURRENT record instead of clobbering the rotated tokens
  // with our stale snapshot (which would leave the next refresh holding a dead
  // token and force a needless re-login). If the record vanished (concurrent
  // purge) don't resurrect it; if another request already backfilled, use theirs.
  const fresh = await store.get(id);
  if (!fresh) return null;
  if (fresh.identity) return fresh.identity;
  await persist(store, id, grantFrom(fresh), fresh, identity);
  return identity;
}

export async function deleteSession(store: SessionStore, id: SessionId): Promise<void> {
  await store.delete(id);
}
