import type { Config } from "./config";
import type { SessionData, SessionStore } from "./store";
import { refresh } from "./oauth";
import * as arctic from "arctic";
import { getLogger } from "@logtape/logtape";

const log = getLogger(["htmldoc-review", "session"]);

export type { SessionData } from "./store";

const DEFAULT_TTL = 60 * 60 * 24 * 180;
const SKEW_MS = 30_000;

function refreshTtlOf(tokens: arctic.OAuth2Tokens): number {
  const t = Number((tokens.data as Record<string, unknown>).refresh_token_expires_in);
  return Number.isFinite(t) ? t : DEFAULT_TTL;
}

export async function createSession(
  store: SessionStore,
  data: SessionData,
  refreshTtlSeconds = DEFAULT_TTL
): Promise<string> {
  // Session id = one crypto.randomUUID(). Per OWASP Session Management, a
  // session id must be generated by a CSPRNG and carry >= 64 bits of entropy;
  // a v4 UUID is CSPRNG-backed with 122 random bits, comfortably clearing the
  // floor, so a single UUID suffices (no need to concatenate two). The id is
  // opaque — it's only a lookup key into the server-side store, never a token.
  const id = crypto.randomUUID();
  await store.put(id, data, refreshTtlSeconds);
  return id;
}

/**
 * Decide whether an arctic error from a refresh means "the grant is dead"
 * (force re-login) versus "transient/unknown" (must surface). A bad/expired/
 * revoked refresh token comes back as OAuth2RequestError (200 + error body) or,
 * for a non-200 token response, UnexpectedResponseError /
 * UnexpectedErrorResponseBodyError in arctic v3. A network failure
 * (ArcticFetchError) is NOT a dead grant.
 */
function isDeadGrant(e: unknown): boolean {
  return (
    e instanceof arctic.OAuth2RequestError ||
    e instanceof arctic.UnexpectedResponseError ||
    e instanceof arctic.UnexpectedErrorResponseBodyError
  );
}

/**
 * Refresh the access token for session `id` and persist the result.
 *
 * Returns the new access token, or `null` to signal "force a full re-login".
 *
 * Shape check (arctic v3): `refresh()` -> `GitHub.refreshAccessToken` -> an
 * `OAuth2Tokens`; we read `accessToken()`, `refreshToken()` (GitHub rotates the
 * refresh token, so we persist the NEW one), and `accessTokenExpiresAt()`.
 *
 * Refresh race (known D1 limitation): with no Durable Object to serialize
 * refreshes, two concurrent requests can both see an expired token; the first
 * rotates the refresh token, and the second's now-stale token fails as a dead
 * grant. So on a dead grant we RE-READ the session once: if a concurrent
 * request already rotated to a fresh, unexpired token, we use it instead of
 * nuking a perfectly good session. Only if the re-read is also gone/expired do
 * we purge and force re-login. A residual race remains (two refreshes can still
 * interleave between the re-read and the delete); accepted without a DO.
 */
async function doRefresh(
  cfg: Config,
  store: SessionStore,
  id: string,
  refreshToken: string
): Promise<string | null> {
  try {
    const tokens = await refresh(cfg, refreshToken);
    const next: SessionData = {
      access_token: tokens.accessToken(),
      refresh_token: tokens.refreshToken(),
      expires_at: tokens.accessTokenExpiresAt().getTime(),
    };
    await store.put(id, next, refreshTtlOf(tokens));
    return next.access_token;
  } catch (e) {
    // A network failure must NOT nuke the session -- let it surface as 5xx.
    if (e instanceof arctic.ArcticFetchError) throw e;
    if (!isDeadGrant(e)) throw e;

    // Possible dead grant. Before purging, re-read once: a concurrent request
    // may have already rotated the token (refresh-race window above).
    const reread = await store.get(id);
    if (reread && Date.now() < reread.expires_at - SKEW_MS) {
      log.info("session refresh lost a race; using concurrently-rotated token", {
        sessionId: id,
      });
      return reread.access_token;
    }

    // Genuinely dead refresh token: purge the session and force a full
    // re-login. Log the session id and error class only -- never the refresh
    // token. Preserve the original arctic error as `cause` so it is not
    // swallowed (e.g. for a future Sentry/breadcrumb hook).
    const cause = e instanceof Error ? e : undefined;
    log.error("session refresh failed; purging session", {
      sessionId: id,
      error: cause?.constructor.name ?? typeof e,
      cause: new Error("refresh token rejected", { cause }),
    });
    await store.delete(id);
    return null;
  }
}

export async function getValidAccessToken(
  cfg: Config,
  store: SessionStore,
  id: string,
  forceRefresh = false
): Promise<string | null> {
  const s = await store.get(id);
  if (!s) return null;

  if (!forceRefresh && Date.now() < s.expires_at - SKEW_MS) {
    return s.access_token;
  }

  return doRefresh(cfg, store, id, s.refresh_token);
}

export async function deleteSession(store: SessionStore, id: string): Promise<void> {
  await store.delete(id);
}
