/// <reference types="@cloudflare/vitest-pool-workers/types" />
// Worker suite for the PUBLIC widget-bundle route at COMMENTS_WIDGET_SRC. Proves the
// Worker serves the checked-in dist bytes with the right content-type and auth
// posture (none), issues ZERO outbound GitHub fetch, 405s a non-GET, and — the
// load-bearing property — has no interplay with the neutral-404 non-leak
// contract. Runs INSIDE Miniflare (like inject.workers.test.ts); GitHub is mocked
// via fetch-mock; sessions are seeded straight into KV.
import {
  env,
  applyD1Migrations,
  createExecutionContext,
  waitOnExecutionContext,
  type D1Migration,
} from "cloudflare:test";
import { beforeAll, afterEach, afterAll, describe, it, expect } from "vitest";
import worker, { type Env } from "../../src/worker/index";
import { COMMENTS_WIDGET_SRC } from "../../src/worker/inject";
// The exact bytes the Worker serves — the same Text-module import inject.ts uses.
import bundleTxt from "../../src/worker/comments.mjs.txt";
import { fetchMock } from "./fetch-mock";

declare module "cloudflare:test" {
  interface ProvidedEnv extends Env {}
}
declare global {
  namespace Cloudflare {
    interface Env {
      TEST_MIGRATIONS: D1Migration[];
    }
  }
}

const ORIGIN = "https://docs.my-org.dev";
const REPO = "app-ios";
const DOC_PATH = "guide.html";
const REF = "main";
const KNOWN_TOKEN = "gho_canned_access_token";
const NEUTRAL_BODY = "Not found or no access";
const SEEDED_IDENTITY = { login: "octocat", name: "Mona Lisa", id: 583231 };
// The banner esbuild stamps on every widget build — a cheap sanity marker.
const BANNER = "AUTOGENERATED FROM src/comments/*.ts";

const bundleUrl = `${ORIGIN}${COMMENTS_WIDGET_SRC}`;
const docUrl = `${ORIGIN}/${REPO}/${DOC_PATH}?ref=${REF}`;

async function seedSession(id: string): Promise<string> {
  await env.SESSIONS.put(
    `sess:${id}`,
    JSON.stringify({
      version: 2,
      iat: Date.now(),
      identity: SEEDED_IDENTITY,
      access_token: KNOWN_TOKEN,
      refresh_token: "refresh_canned",
      expires_at: Date.now() + 3_600_000,
    }),
    { expirationTtl: 3600 },
  );
  return id;
}

function mockProbe(status: number, ref: string | undefined = REF) {
  const query = ref !== undefined ? `?ref=${encodeURIComponent(ref)}` : "";
  fetchMock
    .get("https://api.github.com")
    .intercept({ method: "GET", path: `/repos/${env.REPO_ORG}/${REPO}/contents/${DOC_PATH}${query}` })
    .reply(status, "", { headers: { "content-type": "application/json" } });
}

async function call(url: string, init?: RequestInit): Promise<Response> {
  const ctx = createExecutionContext();
  const res = await worker.fetch(new Request(url, init), env, ctx);
  await waitOnExecutionContext(ctx);
  return res;
}

function withSession(id: string, init: RequestInit = {}): RequestInit {
  return { ...init, headers: { ...(init.headers ?? {}), cookie: `sid=${id}` } };
}

beforeAll(async () => {
  await applyD1Migrations(env.COMMENTS_DB, env.TEST_MIGRATIONS);
  fetchMock.activate();
  fetchMock.disableNetConnect();
});
afterEach(() => {
  // Fails loudly if any test queued an interceptor the run didn't consume — and,
  // combined with disableNetConnect, proves the bundle route made NO outbound
  // call (an unmocked GitHub hit would have thrown inside fetch).
  fetchMock.assertNoPendingInterceptors();
});
afterAll(() => {
  fetchMock.deactivate();
});

describe("widget-bundle route (public, doc-independent)", () => {
  it("GET with NO cookie -> 200 JS bundle byte-matching the checked-in dist", async () => {
    const res = await call(bundleUrl); // no session, no bearer
    expect(res.status).toBe(200);
    expect(res.headers.get("Content-Type")).toBe("application/javascript; charset=utf-8");
    expect(res.headers.get("Cache-Control")).toBe("no-cache");
    const body = await res.text();
    // Byte-identical to the imported Text module (which is the vendored dist).
    expect(body).toBe(bundleTxt);
    // Sanity: it is actually the built widget, not an empty/placeholder string.
    expect(body).toContain(BANNER);
  });

  it("issues ZERO outbound GitHub fetch (never enters the auth/probe path)", async () => {
    // No probe/doc interceptor queued. If the route resolved a token or probed
    // GitHub, disableNetConnect would throw; a clean 200 proves it did neither.
    const res = await call(bundleUrl);
    expect(res.status).toBe(200);
  });

  it("a non-GET (POST) -> 405", async () => {
    const res = await call(bundleUrl, { method: "POST" });
    expect(res.status).toBe(405);
  });

  it("HEAD -> 200 with headers but no body", async () => {
    const res = await call(bundleUrl, { method: "HEAD" });
    expect(res.status).toBe(200);
    expect(res.headers.get("Content-Type")).toBe("application/javascript; charset=utf-8");
    expect(await res.text()).toBe("");
  });
});

describe("non-leak: the bundle route is independent of the neutral-404 deny path", () => {
  for (const status of [403, 404]) {
    it(`a denied doc (probe ${status}) still returns the neutral 404 with no widget markup`, async () => {
      await seedSession(`s-deny-${status}`);
      // ONLY a probe interceptor: if serveDoc ran, its unmocked fetch would trip
      // net-disabled; afterEach confirms the probe was consumed.
      mockProbe(status);
      const res = await call(docUrl, withSession(`s-deny-${status}`));
      expect(res.status).toBe(404);
      const body = await res.text();
      expect(body).toBe(NEUTRAL_BODY);
      // The deny path carries no seed, no widget script, and no bundle bytes.
      expect(body).not.toContain("__htmldocs_comments");
      expect(body).not.toMatch(/<script type="module"/);
      expect(body).not.toContain(BANNER);
    });
  }

  it("COMMENTS_WIDGET_SRC and a neutral-404 doc response share no markup", async () => {
    await seedSession("s-independent");
    mockProbe(404);
    const denied = await call(docUrl, withSession("s-independent"));
    const deniedBody = await denied.text();

    const bundle = await call(bundleUrl);
    const bundleBody = await bundle.text();

    expect(denied.status).toBe(404);
    expect(bundle.status).toBe(200);
    // The bundle route adds no widget markup to the deny path, and vice versa.
    expect(deniedBody).toBe(NEUTRAL_BODY);
    expect(bundleBody).not.toContain(NEUTRAL_BODY);
    expect(bundleBody).toContain(BANNER);
  });
});
